#version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - .env
    volumes:
      - ./mysql_dump.sql:/docker-entrypoint-initdb.d/mysql_dump.sql
    ports:
      - "3306:3306"
